### ISSUE TITLE
ASU... choose font and color for prosemirror content

### ISSUE THREAD

**Issue by simonaudet** [Omerlo-Technologies/ex_prosemirror#52]
**Description**
Add the ability to provide prosemirror a list of fonts and colors to support. 

**Acceptance criteria**
* At initialization, allow a list of fonts and colors to be provided. 
* When editing regular text content (not headers), the user can select a font and color from those provided. 
* The first font and color is selected by default. 
* If no color or font is provided, Prosemirror shows no options and assume the client will set properly.

**Comment by Matsa59** [comment]
It's already supported thanks to marks. Add a color mark could be nice

**Comment by simonaudet** [comment]
Nice but pay attention to acceptance criterias. It's not any font, but a given set of fonts.

**Comment by Matsa59** [comment]
Yeah we should provide a filter system or something like that
