### ISSUE TITLE
ASU... choose zone for prosemirror content

### ISSUE THREAD

**Issue by simonaudet** [Omerlo-Technologies/ex_prosemirror#53]
**Description**
Zones can be assigned to all blocks in prosemirror. 

**Acceptance criteria**
* At initialization, allow a list of zones to be provided.
* At the top right of all blocks in prosemirror, show  a badge indicated the zone for the block. Clicking on the zone cycle through available zones.
* The first zone is selected by default. 
* If no zones are provided, Prosemirror shows no options and assume the client will set properly.

**Comment by Matsa59** [comment]
Not depends of this lib ;)
